### ISSUE TITLE
Dashboard layout screwed up in Firefox

### ISSUE THREAD

**Issue by tjvantoll** [telerik/react-coffee-warehouse#3]
Hey all,

fyi the grid does not stay within its container in Firefox, which messes up the layout of the entire page.

![Screen Shot 2020-05-27 at 9 19 59 AM](https://user-images.githubusercontent.com/544280/83023762-5af78500-9ffb-11ea-8999-a7e643345de3.png)

**Comment by silviyaboteva** [comment]
It was caused due to the horizontal overflow of the Grid. It's fixed now.
