### ISSUE TITLE
Drawer breaks on small viewport

### ISSUE THREAD

**Issue by luislinietsky** [telerik/react-coffee-warehouse#4]
Hi,

Great product. I am looking forward to test it in a new project.

However, I think a found an issue/bug. 

If I open https://telerik.github.io/react-coffee-warehouse in a mobile device like a mobile phone or make the browser window in the PC too narrow, drawer menu disappears and a black overlay appears on top of the website.

This way the drawer and its contents are no longer available.

Expected behavior would be to keep showing the drawer, even if it is on a different format for mobile. However, If such functionality or configuration do exist, it should be available in the demo too.

Thanks in advance,
Luis

**Comment by silviyaboteva** [comment]
Hello Luis,
This issue is addressed by the following commit: 6971f3f6dffd67095baeedd53a67c1f0da2c2e5f.
